### ISSUE TITLE
[HDBDD] Issue with handling a tableType

### ISSUE THREAD

**Issue by mvmanov** [SAP/xsk#1201] opened 2022-02-04 09:02 UTC
**sample.hdbdd**:
```
@GenerateTableType : false
type sampleType {
    "CREATED_ON": UTCTimestamp;
    "CREATED_BY": String(20);
    "LAST_UPDATED_ON": UTCTimestamp;
    "LAST_UPDATED_BY": String(20);
    "STATUS": String(1);
};

@Catalog.tableType : #ROW
ENTITY SAMPLE {  
    "FIELD": sampleType ;
}
```

**Exception**:
```java
2022-02-04 08:59:02.586 [ERROR] [pool-256940-thread-1] c.s.x.h.d.p.t.XSKTableCreateProcessor - CREATE COLUMN TABLE ...." ( "FIELD.CREATED_ON" TIMESTAMP  , "FIELD.CREATED_BY" NVARCHAR (20) , "FIELD.LAST_UPDATED_ON" TIMESTAMP  , "FIELD.LAST_UPDATED_BY" NVARCHAR (20) , "FIELD.STATUS" NVARCHAR (1) )
2022-02-04 08:59:02.586 [ERROR] [pool-256940-thread-1] c.s.x.h.d.p.t.XSKTableCreateProcessor - SAP DBTech JDBC: [257]: sql syntax error: unterminated quoted identifier: line 1 col 73 (at pos 73)
com.sap.db.jdbc.exceptions.JDBCDriverException: SAP DBTech JDBC: [257]: sql syntax error: unterminated quoted identifier: line 1 col 73 (at pos 73)
        at com.sap.db.jdbc.exceptions.SQLExceptionSapDB._newInstance(SQLExceptionSapDB.java:209) ~[ngdbc-2.11.14.jar:na]
        at com.sap.db.jdbc.exceptions.SQLExceptionSapDB.newInstance(SQLExceptionSapDB.java:42) ~[ngdbc-2.11.14.jar:na]
        at com.sap.db.jdbc.packet.HReplyPacket._buildExceptionChain(HReplyPacket.java:841) ~[ngdbc-2.11.14.jar:na]
```

**Comment by dpanayotov** [comment] 2022-02-09 13:13
duplicate of
- #1182

**Closed by dpanayotov** 2022-02-09 13:13 UTC
Labels: priority-medium, effort-medium, customer
